site_name: spend-analysis
repo_url: https://github.com/EliasFM/spend-analysis
site_url: https://EliasFM.github.io/spend-analysis
site_description: Analysis of CC spend
site_author: Elias Mendel
edit_uri: edit/main/docs/
repo_name: EliasFM/spend-analysis
copyright: Maintained by <a href="https://EliasFM.com">EliasFM</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [spend_analysis]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EliasFM/spend-analysis
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/spend-analysis

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
